### ISSUE TITLE
I'm far too stupid to follow your instructions

### ISSUE THREAD

**Issue by nickpullar** [irisiflimsi/harn-webmap#1]
Hi!

I can't find another way to communicate with you :)

I found your Harn Geomap page, and it seems like it could be a very worthwhile resource for me.

I downloaded all the apps, the zip file (which seems to be missing the images folder).

I have set up the Geoserver as you suggest, and I have QGIS.

However, in Geoserver, when I use the URL "http://localhost:8080/geoserver/www/kethira/maps.html", I only get a big blue rectangle.

I am sure I have not completed all the steps (although I tried).

Please let me know:

1) How can I download the tiffs (I seem to have none, which is why the Geoserver is the big blue rectange)
2) How can I then use the QGIS tool

Many thanks!

Nick Pullar

**Comment by irisiflimsi** [comment]
That's okay. Sometimes I'm too stupid to give correct instructions. I'm also reachable through the Harnforum as Irisi Flimsi. Or use my email address miju (at) phantasia.org directly.

There is a reason why they are missing, I don't hold the rights to the images and I cannot share them in this way. Only the few (fan) images I created myself I can share. Contact me directly, maybe we can work out something.

The blue screen actually means, everything is okay. The images I released are invisible at that level. If you open them all in Qqis, you should see a lot of dots strewn about and you can center on them.

Images should appear (and in parallel directories) when you downloaded them, e.g. https://github.com/irisiflimsi/harn-geomap/tree/master/workspaces/images/local appears in the workspaces/.../local directory after unzipping.

Either start Qgis with all of them on the command line or open them as raster images when you started Qgis any other way.

For more details get in contact through email. Sorry for the late answer, I was offline for two weeks.

Cheers,
Michael

**Comment by irisiflimsi** [comment]
I have added a low-res Harnmap tif with the correct coordinates, so you no longer need to hunt for any coordinates in QGis. I also added the vector data for the points of interests, for which I have created coordinates (either in the autolist or points subdirectory).

I am going to close the issue for now.

**Comment by irisiflimsi** [comment]
.
